"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
exports.__esModule = true;
exports.example = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: example.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
var pb_1 = require("google-protobuf");
var example;
(function (example) {
    var _Example_one_of_decls;
    var Example = /** @class */ (function (_super) {
        __extends(Example, _super);
        function Example(data) {
            var _this = _super.call(this) || this;
            _Example_one_of_decls.set(_this, []);
            pb_1.Message.initialize(_this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(_this, _Example_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("bigInt" in data && data.bigInt != undefined) {
                    _this.bigInt = data.bigInt;
                }
            }
            return _this;
        }
        Object.defineProperty(Example.prototype, "bigInt", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 1, "0");
            },
            set: function (value) {
                pb_1.Message.setField(this, 1, value);
            },
            enumerable: false,
            configurable: true
        });
        Example.fromObject = function (data) {
            var message = new Example({});
            if (data.bigInt != null) {
                message.bigInt = data.bigInt;
            }
            return message;
        };
        Example.prototype.toObject = function () {
            var data = {};
            if (this.bigInt != null) {
                data.bigInt = this.bigInt;
            }
            return data;
        };
        Example.prototype.serialize = function (w) {
            var writer = w || new pb_1.BinaryWriter();
            if (this.bigInt != "0")
                writer.writeUint64String(1, this.bigInt);
            if (!w)
                return writer.getResultBuffer();
        };
        Example.deserialize = function (bytes) {
            var reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Example();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.bigInt = reader.readUint64String();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        };
        Example.prototype.serializeBinary = function () {
            return this.serialize();
        };
        Example.deserializeBinary = function (bytes) {
            return Example.deserialize(bytes);
        };
        return Example;
    }(pb_1.Message));
    _Example_one_of_decls = new WeakMap();
    example.Example = Example;
})(example = exports.example || (exports.example = {}));
