/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: example.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace example {
    export class Example extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            bigInt?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("bigInt" in data && data.bigInt != undefined) {
                    this.bigInt = data.bigInt;
                }
            }
;        }
        get bigInt() {
            return pb_1.Message.getFieldWithDefault(this, 1, "0") as string;
        }
        set bigInt(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            bigInt?: string;
        }): Example {
            const message = new Example({});
            if (data.bigInt != null) {
                message.bigInt = data.bigInt;
            }
            return message;
        }
        toObject() {
            const data: {
                bigInt?: string;
            } = {};
            if (this.bigInt != null) {
                data.bigInt = this.bigInt;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.bigInt != "0")
                writer.writeUint64String(1, this.bigInt);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Example {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Example();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.bigInt = reader.readUint64String();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Example {
            return Example.deserialize(bytes);
        }
    }
}
